import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/navBar';
import Footer from '@/components/footer';
import Image from 'next/image';
import bg1 from '../public/background.png';
const open_sans = Open_Sans({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, intiial-scale=1.0"
      />
      {/* bg-gray-200 separator */}
      <body className={`${open_sans.className} antialiased bg-gray-100`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
