import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/navBar';
import Footer from '@/components/footer';

const lato = Lato({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, intiial-scale=1.0"
      />

      <body className={`${lato.className} antialiased bg-blue-100`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
